backend:
  name: git-gateway
  branch: master

media_folder: static/assets/img
public_folder: /assets/img

collections:
  - name: 'bios'
    label: 'Bios'
    label_singular: 'Bio'
    folder: 'content/bios'
    format: 'frontmatter'
    create: false
    slug: '{{slug}}' #'{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Avatar', name: 'avatar', widget: 'image', allow_multiple: false, choose_url: false, media_folder: '/assets/img/bios' }
      - { label: 'Website', name: 'website', widget: 'string', required: false }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - { label: 'YouTube', name: 'youtube', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', buttons: ['bold', 'italic', 'link', 'quote', 'bulleted-list', 'numbered-list'], editor_components: ['image'] }