backend:
  name: git-gateway
  branch: master

media_folder: static/assets/img
public_folder: /assets/img

collections:
  - name: 'bios'
    label: 'Bios'
    label_singular: 'Bio'
    folder: 'content/bios'
    format: 'frontmatter'
    create: true
    slug: {{slug}} #'{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Website', name: 'soc-wb', widget: 'string', required: false }
      - { label: 'Twitter', name: 'soc-tw', widget: 'string', required: false }
      - { label: 'Facebook', name: 'soc-fb', widget: 'string', required: false }
      - { label: 'YouTube', name: 'soc-yt', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }